# Generated by Django 3.2 on 2022-09-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science', models.BooleanField(default=False, verbose_name='Есть наука')),
                ('interesting', models.BooleanField(default=False, verbose_name='Интересный')),
                ('difficult', models.BooleanField(default=False, verbose_name='Сложный')),
                ('unclear', models.BooleanField(default=False, verbose_name='Непонятный')),
                ('repeat', models.BooleanField(default=False, verbose_name='Повтор')),
            ],
        ),
        migrations.CreateModel(
            name='NiokrCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science', models.BooleanField(default=False, verbose_name='Есть наука')),
                ('interesting', models.BooleanField(default=False, verbose_name='Интересный')),
                ('difficult', models.BooleanField(default=False, verbose_name='Сложный')),
                ('unclear', models.BooleanField(default=False, verbose_name='Непонятный')),
                ('repeat', models.BooleanField(default=False, verbose_name='Повтор')),
            ],
        ),
        migrations.CreateModel(
            name='NiokrProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(db_index=True, max_length=150, verbose_name='Тема НИОКР')),
                ('data_project_start', models.DateField(verbose_name='Дата начала исследований (ДД.ММ.ГГГГ)')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт проекта (при наличии)')),
                ('base_organisation', models.CharField(db_index=True, max_length=150, verbose_name='Базовая организация')),
                ('science_novelty', models.CharField(db_index=True, max_length=150, verbose_name='Научная новизна')),
                ('commercial_result', models.CharField(db_index=True, max_length=150, verbose_name='Коммерческий результат')),
                ('equipment', models.CharField(db_index=True, max_length=150, verbose_name='Оборудование, необходимое для реализации проекта')),
                ('grants', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Наличие грантов')),
                ('patents', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Наличие патента')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='niokr_project_photos/', verbose_name='Обложка')),
                ('annotation', models.TextField(max_length=2000, verbose_name='Аннотация к проекту (до 2000 символов)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('hex_color', models.CharField(blank=True, default='', max_length=20, verbose_name='Hex цвет')),
                ('science', models.IntegerField(default=0, verbose_name='Наука')),
                ('interesting', models.IntegerField(default=0, verbose_name='Интересный')),
                ('difficult', models.IntegerField(default=0, verbose_name='Сложный')),
                ('unclear', models.IntegerField(default=0, verbose_name='Непонятный')),
                ('repeat', models.IntegerField(default=0, verbose_name='Повтор')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NiokrUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Фио')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('academic_degrees', models.TextField(blank=True, null=True, verbose_name='Ученые степени')),
                ('academic_titles', models.TextField(blank=True, null=True, verbose_name='Ученые звания')),
                ('is_responsible', models.BooleanField(default=False, verbose_name='Научный руководитель')),
                ('ec_id', models.IntegerField(blank=True, null=True, verbose_name='ID пользователя в системе эффективного контракта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название проекта')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='project_photos/', verbose_name='Обложка')),
                ('site', models.URLField(verbose_name='Ссылка на сайт проекта')),
                ('description', models.TextField(verbose_name='Описание продукта/сервиса')),
                ('note', models.CharField(max_length=150, verbose_name='Примечание к проекту')),
                ('tag', models.TextField(blank=True, choices=[('Софт Проект', 'Софт Проект'), ('Программно-аппаратный комплекс', 'Программно-аппаратный комплекс')], null=True, verbose_name='Тип проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('hex_color', models.CharField(blank=True, default='', max_length=20, verbose_name='Hex цвет')),
                ('science', models.IntegerField(default=0, verbose_name='Наука')),
                ('interesting', models.IntegerField(default=0, verbose_name='Интересный')),
                ('difficult', models.IntegerField(default=0, verbose_name='Сложный')),
                ('unclear', models.IntegerField(default=0, verbose_name='Непонятный')),
                ('repeat', models.IntegerField(default=0, verbose_name='Повтор')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
